name: 'Create homepage bookmark config'
description: 'Create homepage bookmark config'
author: 'Alexey Savelyev'
inputs:
    directory:
        description: 'Target directory'
        required: true
    filename:
        description: 'Target file name'
        required: true
    domain_name:
        description: 'Service domain name'
        required: true
    server_local_ip:
        description: 'Server IP in local network'
        required: true
    service_port:
        description: 'Service port in local network'
        required: true
    server_host:
        description: 'Server IP in VPN network'
        required: true

runs:
    using: 'composite'
    steps:
        -   name: Check existing homepage bookmark config
            shell: bash
            run: |
                if test -f ${{inputs.directory}}/${{inputs.filename}}
                then
                    echo "LOCAL_CONFIG_IS_EXIST=true" >> ${GITHUB_ENV}
                else
                    echo "LOCAL_CONFIG_IS_EXIST=false" >> ${GITHUB_ENV}
                fi

        -   name: Delete old homepage bookmark config
            shell: bash
            if: ${{env.LOCAL_CONFIG_IS_EXIST == 'true'}}
            run : |
                cd ${{inputs.directory}}
                [ -e ./${{inputs.filename}} ] && sudo rm -rf ./${{inputs.filename}}

        -   name: Create config directory
            shell: bash
            if: ${{env.LOCAL_CONFIG_IS_EXIST == 'false'}}
            run : |
                mkdir -p ${{inputs.directory}}

        -   name: Create new homepage bookmark config
            shell: bash
            run : |
                cd ${{inputs.directory}}
                touch ./${{inputs.filename}}
                echo "    - ${{inputs.domain_name}}:" >> ./${{inputs.filename}}
                echo "        - abbr: L" >> ./${{inputs.filename}}
                echo "          href: http://${{inputs.server_local_ip}}:${{inputs.service_port}}" >> ./${{inputs.filename}}
                echo "    - ${{inputs.domain_name}}:" >> ./${{inputs.filename}}
                echo "        - abbr: V" >> ./${{inputs.filename}}
                echo "          href: http://${{inputs.server_host}}:${{inputs.service_port}}" >> ./${{inputs.filename}}
                echo "    - ${{inputs.domain_name}}:" >> ./${{inputs.filename}}
                echo "        - abbr: D" >> ./${{inputs.filename}}
                echo "          href: http://${{inputs.domain_name}}" >> ./${{inputs.filename}}